### ISSUE TITLE
We can not interact with top elements of application

### ISSUE THREAD

**Issue by duizabojul** [Silver-Smok/silverstock-electron-app#11]
![image](https://github.com/Silver-Smok/silverstock-electron-app/assets/7392946/5a5a7a9b-044d-4295-9136-c7aa222601ef)

Some buttons here are not clickable. We need to add a `no-drag` property on some elements

**Comment by Zinoka** [comment]
Hello, which buttons are not clickable ? I've tried on my side, and all buttons work.

**Comment by Zinoka** [comment]
Pull request created. Waiting for review and merge.

**Comment by Zinoka** [comment]
Deployed and merged.
